//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation:.
        /// </summary>
        public static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation registration.
        /// </summary>
        public static string Accommodation_registration {
            get {
                return ResourceManager.GetString("Accommodation_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation reviews.
        /// </summary>
        public static string Accommodation_reviews {
            get {
                return ResourceManager.GetString("Accommodation_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation statistic.
        /// </summary>
        public static string Accommodation_statistic {
            get {
                return ResourceManager.GetString("Accommodation_statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation type:.
        /// </summary>
        public static string Accommodation_type {
            get {
                return ResourceManager.GetString("Accommodation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new property to your list of accommodations.
        /// </summary>
        public static string Add_new_property_to_your_list_of_accommodations {
            get {
                return ResourceManager.GetString("Add_new_property_to_your_list_of_accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string Add_note {
            get {
                return ResourceManager.GetString("Add_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comment:.
        /// </summary>
        public static string Additional_comment {
            get {
                return ResourceManager.GetString("Additional_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reservations.
        /// </summary>
        public static string All_reservations {
            get {
                return ResourceManager.GetString("All_reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avrage rating:.
        /// </summary>
        public static string Avrage_rating {
            get {
                return ResourceManager.GetString("Avrage_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisiest month:.
        /// </summary>
        public static string Buisiest_month {
            get {
                return ResourceManager.GetString("Buisiest_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisiest year.
        /// </summary>
        public static string Buisiest_year {
            get {
                return ResourceManager.GetString("Buisiest_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        public static string Cancel_reservation {
            get {
                return ResourceManager.GetString("Cancel_reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation period:.
        /// </summary>
        public static string Cancelation_period {
            get {
                return ResourceManager.GetString("Cancelation_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application language.
        /// </summary>
        public static string Change_application_language {
            get {
                return ResourceManager.GetString("Change_application_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application theme.
        /// </summary>
        public static string Change_application_theme {
            get {
                return ResourceManager.GetString("Change_application_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ussername and password.
        /// </summary>
        public static string Change_username_and_password {
            get {
                return ResourceManager.GetString("Change_username_and_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string Choose_lanugage {
            get {
                return ResourceManager.GetString("Choose_lanugage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanlines:.
        /// </summary>
        public static string Cleanlines {
            get {
                return ResourceManager.GetString("Cleanlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left to rate guest:.
        /// </summary>
        public static string Days_left_to_rate_guest {
            get {
                return ResourceManager.GetString("Days_left_to_rate_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished:.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a pdf report for a renovations.
        /// </summary>
        public static string Generate_a_pdf_report_for_a_renovations {
            get {
                return ResourceManager.GetString("Generate_a_pdf_report_for_a_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report.
        /// </summary>
        public static string Generate_report {
            get {
                return ResourceManager.GetString("Generate_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Go back.
        /// </summary>
        public static string Go_back {
            get {
                return ResourceManager.GetString("Go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest username:.
        /// </summary>
        public static string Guest_username {
            get {
                return ResourceManager.GetString("Guest_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle rescheduling.
        /// </summary>
        public static string Handle_rescheduling {
            get {
                return ResourceManager.GetString("Handle_rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all requests for rescheduling reservations.
        /// </summary>
        public static string Here_you_can_see_all_requests_for_rescheduling_reservations {
            get {
                return ResourceManager.GetString("Here_you_can_see_all_requests_for_rescheduling_reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all reservations that gusts have made.
        /// </summary>
        public static string Here_you_can_see_all_reservations_that_gusts_have_made {
            get {
                return ResourceManager.GetString("Here_you_can_see_all_reservations_that_gusts_have_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see guests that you still haven&apos;t rated, and rate them.
        /// </summary>
        public static string Here_you_can_see_guests_that_you_still_havent_rated_and_rate_them {
            get {
                return ResourceManager.GetString("Here_you_can_see_guests_that_you_still_havent_rated_and_rate_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see ratings and reviews that guests have left.
        /// </summary>
        public static string Here_you_can_see_ratings_and_reviews_that_guests_have_left {
            get {
                return ResourceManager.GetString("Here_you_can_see_ratings_and_reviews_that_guests_have_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgaes url:.
        /// </summary>
        public static string Images_url {
            get {
                return ResourceManager.GetString("Images_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial dates.
        /// </summary>
        public static string Initial_date {
            get {
                return ResourceManager.GetString("Initial_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is already ocupied:.
        /// </summary>
        public static string Is_already_ocupied {
            get {
                return ResourceManager.GetString("Is_already_ocupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is super owner:.
        /// </summary>
        public static string Is_super_owner {
            get {
                return ResourceManager.GetString("Is_super_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of guests:.
        /// </summary>
        public static string Maximum_number_of_guests {
            get {
                return ResourceManager.GetString("Maximum_number_of_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum renovation days:.
        /// </summary>
        public static string Minimum_renovation_days {
            get {
                return ResourceManager.GetString("Minimum_renovation_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ratings.
        /// </summary>
        public static string My_ratings {
            get {
                return ResourceManager.GetString("My_ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyAccommodations.
        /// </summary>
        public static string MyAccommodations {
            get {
                return ResourceManager.GetString("MyAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New date.
        /// </summary>
        public static string New_date {
            get {
                return ResourceManager.GetString("New_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New forum notification.
        /// </summary>
        public static string New_forum_notification {
            get {
                return ResourceManager.GetString("New_forum_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New renovations.
        /// </summary>
        public static string New_renovations {
            get {
                return ResourceManager.GetString("New_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cancelations:.
        /// </summary>
        public static string Number_of_cancelations {
            get {
                return ResourceManager.GetString("Number_of_cancelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        public static string Number_of_guests {
            get {
                return ResourceManager.GetString("Number_of_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of renovations:.
        /// </summary>
        public static string Number_of_renovations {
            get {
                return ResourceManager.GetString("Number_of_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reschedules:.
        /// </summary>
        public static string Number_of_reschedules {
            get {
                return ResourceManager.GetString("Number_of_reschedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reservations:.
        /// </summary>
        public static string Number_of_reservations {
            get {
                return ResourceManager.GetString("Number_of_reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner fairnes:.
        /// </summary>
        public static string Owner_fairnes {
            get {
                return ResourceManager.GetString("Owner_fairnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string Personal_info {
            get {
                return ResourceManager.GetString("Personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate a guest.
        /// </summary>
        public static string Rate_a_guest {
            get {
                return ResourceManager.GetString("Rate_a_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate_guests.
        /// </summary>
        public static string Rate_guests {
            get {
                return ResourceManager.GetString("Rate_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for declining: .
        /// </summary>
        public static string Reason_for_declining {
            get {
                return ResourceManager.GetString("Reason_for_declining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrate.
        /// </summary>
        public static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrate new accommodation.
        /// </summary>
        public static string Registrate_new_accommodation {
            get {
                return ResourceManager.GetString("Registrate_new_accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration sugestion.
        /// </summary>
        public static string Registration_sugestion {
            get {
                return ResourceManager.GetString("Registration_sugestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation.
        /// </summary>
        public static string Renovation {
            get {
                return ResourceManager.GetString("Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation description.
        /// </summary>
        public static string Renovation_description {
            get {
                return ResourceManager.GetString("Renovation_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation length:.
        /// </summary>
        public static string Renovation_length {
            get {
                return ResourceManager.GetString("Renovation_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recomendations.
        /// </summary>
        public static string Renovation_recomendations {
            get {
                return ResourceManager.GetString("Renovation_recomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation reports.
        /// </summary>
        public static string Renovation_reports {
            get {
                return ResourceManager.GetString("Renovation_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation rescheduling.
        /// </summary>
        public static string Renovation_rescheduling {
            get {
                return ResourceManager.GetString("Renovation_rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation sugestions.
        /// </summary>
        public static string Renovation_sugestions {
            get {
                return ResourceManager.GetString("Renovation_sugestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation urgency:.
        /// </summary>
        public static string Renovation_urgency {
            get {
                return ResourceManager.GetString("Renovation_urgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovations.
        /// </summary>
        public static string Renovations {
            get {
                return ResourceManager.GetString("Renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation rescheduling.
        /// </summary>
        public static string Reservation_rescheduling {
            get {
                return ResourceManager.GetString("Reservation_rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review date:.
        /// </summary>
        public static string Review_date {
            get {
                return ResourceManager.GetString("Review_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule following:.
        /// </summary>
        public static string Rule_following {
            get {
                return ResourceManager.GetString("Rule_following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule renovation.
        /// </summary>
        public static string Schedule_renovation {
            get {
                return ResourceManager.GetString("Schedule_renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule renovation for one of your accommodations.
        /// </summary>
        public static string Schedule_renovation_for_one_of_your_accomodations {
            get {
                return ResourceManager.GetString("Schedule_renovation_for_one_of_your_accomodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled renovations.
        /// </summary>
        public static string Scheduled_renovations {
            get {
                return ResourceManager.GetString("Scheduled_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See accommodations.
        /// </summary>
        public static string See_accommodations {
            get {
                return ResourceManager.GetString("See_accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all accommodations that you own.
        /// </summary>
        public static string See_all_accommodations_that_you_own {
            get {
                return ResourceManager.GetString("See_all_accommodations_that_you_own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all scheduled renovations.
        /// </summary>
        public static string See_all_scheduled_renovations {
            get {
                return ResourceManager.GetString("See_all_scheduled_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all statistic for your accommodations.
        /// </summary>
        public static string See_all_statistic_for_your_accommodations {
            get {
                return ResourceManager.GetString("See_all_statistic_for_your_accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See forums.
        /// </summary>
        public static string See_forums {
            get {
                return ResourceManager.GetString("See_forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See images.
        /// </summary>
        public static string See_images {
            get {
                return ResourceManager.GetString("See_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See recommendations.
        /// </summary>
        public static string See_reccommendations {
            get {
                return ResourceManager.GetString("See_reccommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See requests.
        /// </summary>
        public static string See_requests {
            get {
                return ResourceManager.GetString("See_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See_reservations.
        /// </summary>
        public static string See_reservations {
            get {
                return ResourceManager.GetString("See_reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See reviews.
        /// </summary>
        public static string See_reviews {
            get {
                return ResourceManager.GetString("See_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See scheduled renovations.
        /// </summary>
        public static string See_scheduled_renovations {
            get {
                return ResourceManager.GetString("See_scheduled_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See statistics.
        /// </summary>
        public static string See_statistics {
            get {
                return ResourceManager.GetString("See_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See statistics by months.
        /// </summary>
        public static string See_statistics_by_months {
            get {
                return ResourceManager.GetString("See_statistics_by_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See sugestions.
        /// </summary>
        public static string See_sugestions {
            get {
                return ResourceManager.GetString("See_sugestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See sugestions for renovations that guests have left.
        /// </summary>
        public static string See_sugestions_for_renovations_that_guests_have_left {
            get {
                return ResourceManager.GetString("See_sugestions_for_renovations_that_guests_have_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a month you want to see statistic for.
        /// </summary>
        public static string Select_a_month_you_want_to_see_statistic_for {
            get {
                return ResourceManager.GetString("Select_a_month_you_want_to_see_statistic_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select available date:.
        /// </summary>
        public static string Select_available_date {
            get {
                return ResourceManager.GetString("Select_available_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date range for renovations.
        /// </summary>
        public static string Select_date_range_for_renovations {
            get {
                return ResourceManager.GetString("Select_date_range_for_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected accommodation.
        /// </summary>
        public static string Selected_accommodation {
            get {
                return ResourceManager.GetString("Selected_accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic by months.
        /// </summary>
        public static string Statistic_by_months {
            get {
                return ResourceManager.GetString("Statistic_by_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stayed at:.
        /// </summary>
        public static string Stayed_at {
            get {
                return ResourceManager.GetString("Stayed_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestions for opening new accommodations.
        /// </summary>
        public static string Sugestions_for_opening_new_accommodations {
            get {
                return ResourceManager.GetString("Sugestions_for_opening_new_accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion for renovations.
        /// </summary>
        public static string Suggestion_for_renovations {
            get {
                return ResourceManager.GetString("Suggestion_for_renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Unrated_guest {
            get {
                return ResourceManager.GetString("Unrated_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrated guests.
        /// </summary>
        public static string Unrated_guests {
            get {
                return ResourceManager.GetString("Unrated_guests", resourceCulture);
            }
        }
    }
}
